### ISSUE TITLE
Error during run when second input added 

### ISSUE THREAD

**Issue by sivanni** [sivanni/CXSystem_Git#26]
When this line
S,ge,0,3,Fixed,0.4,4,N/A,0,0,
is added to Burbank_model.csv as the 12th line (adding input from video input to BC cell group)  I get the error (below). This prevents from trying feedforward inhibition.
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/user/1189968/brian_debug_EjCczY.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/user/1189968/brian_script_UfD2in.py Thanks! [brian2]
Traceback (most recent call last):
  File "/opt2/Laskenta_models_on_ssd/CXSystem_Git/cortical_system.py", line 1223, in <module>
    CM = cortical_system(os.path.dirname(os.path.realpath(__file__)) + '/Burbank_config.csv', device='Cpp',runtime = 300 * msecond)
  File "/opt2/Laskenta_models_on_ssd/CXSystem_Git/cortical_system.py", line 138, in __init__
    self.configuration_executer(self.configuration_file)
  File "/opt2/Laskenta_models_on_ssd/CXSystem_Git/cortical_system.py", line 159, in configuration_executer
    self._options[_splitted_line[0]]()
  File "/opt2/Laskenta_models_on_ssd/CXSystem_Git/cortical_system.py", line 752, in synapse
    % (S_name, _pre_group_idx, _post_group_idx,SE_name, SPre_name, SNS_name)
  File "<string>", line 1, in <module>
NameError: name 'awaiting_video_group' is not defined

**Comment by Vafa-Andalibi** [comment]
Fixed, tested.
